live_config_reload: true

env:
  TERM: xterm-256color

window:
  startup_mode: Fullscreen

font:
  normal:
    family: SauceCodePro Nerd Font
  size: 15
  offset:
    y: 4
  builtin_box_drawing: true
