#!/usr/bin/env sh

# give additional premissions
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# tiling options
yabai -m config layout                       bsp
yabai -m config top_padding                  16
yabai -m config bottom_padding               16
yabai -m config left_padding                 16
yabai -m config right_padding                16
yabai -m config window_gap                   16
yabai -m config window_placement             second_child
yabai -m config auto_balance                 on
yabai -m config split_ratio                  0.50

# mouse support
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off

# window modifications
yabai -m config window_topmost               on
yabai -m config window_shadow                float
yabai -m config window_opacity               on
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0

# status bar
yabai -m config external_bar                 off

# ignore apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Alfred Preferences$" manage=off
yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add app="^CleanShot X$" manage=off
yabai -m rule --add app="^TeamViewer$" manage=off
